// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qvwnmpgkaugmbtvxlvlv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InF2d25tcGdrYXVnbWJ0dnhsdmx2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIwNTA1MTQsImV4cCI6MjA2NzYyNjUxNH0.BMrQMQhj2HimcAA59yD8Vy1ddJzg69GKdyyn-KRGTjo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});